In [1]:
pip install -U scikit-learn

Requirement already satisfied: scikit-learn in c:\users\thril\anaconda3\lib\site-packages (1.3.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\thril\anaconda3\lib\site-packages (from scikit-learn) (2.2.0)
Requirement already satisfied: scipy>=1.5.0 in c:\users\thril\anaconda3\lib\site-packages (from scikit-learn) (1.9.1)
Requirement already satisfied: joblib>=1.1.1 in c:\users\thril\anaconda3\lib\site-packages (from scikit-learn) (1.3.1)
Requirement already satisfied: numpy>=1.17.3 in c:\users\thril\anaconda3\lib\site-packages (from scikit-learn) (1.21.5)
Note: you may need to restart the kernel to use updated packages.

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [29]:
df=pd.read_csv("C:/Users/thril/Downloads/play_tennis.csv")

In [30]:
df

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [31]:
t=LabelEncoder()
df=df.apply(t.fit_transform)
df

    day  outlook  temp  humidity  wind  play
0     0        2     1         0     1     0
1     6        2     1         0     0     0
2     7        0     1         0     1     1
3     8        1     2         0     1     1
4     9        1     0         1     1     1
5    10        1     0         1     0     0
6    11        0     0         1     0     1
7    12        2     2         0     1     0
8    13        2     0         1     1     1
9     1        1     2         1     1     1
10    2        2     2         1     0     1
11    3        0     2         0     0     1
12    4        0     1         1     1     1
13    5        1     2         0     0     0

In [41]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [42]:
model=GaussianNB()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

In [43]:
print("precision:",precision_score(y_pred,y_test))
print("Recall:",recall_score(y_pred,y_test))

precision: 0.75
Recall: 1.0